/**
 * robots.txt — auto-generated by Next.js App Router at /robots.txt.
 *
 * Policy:
 *   - All crawlers welcome on public pages.
 *   - Block API endpoints, Next.js internal routes, and any future
 *     /admin or /studio paths.
 *   - Point crawlers explicitly at the sitemap so they don't have to
 *     guess.
 *
 * Note on `host`:
 *   Yandex (and a few others) honour a `host` directive to declare the
 *   canonical domain. Modern Google ignores it but it doesn't hurt and
 *   we have a meaningful Russian-speaking audience for PortoPrime.
 */

import type { MetadataRoute } from 'next';
import { SITE_URL } from '@/lib/site';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow:    '/',
        disallow: [
          '/api/',     // server endpoints — never index
          '/_next/',   // Next.js internals (build artifacts, prefetch)
          '/admin/',   // future admin area placeholder
          '/studio/',  // future CMS placeholder
        ],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host:    SITE_URL,
  };
}
