import { NextRequest, NextResponse } from 'next/server';
import {
  sendContactEvent,
  sendCompleteRegistrationEvent,
  type CapiUserData,
  type CapiUtmData,
} from '@/lib/meta-capi';

// ─── Runtime: standard Node.js (not edge) ──────────────────────────────────
// Required for crypto used by CAPI hashing and the Resend SDK.
export const runtime = 'nodejs';

// ─── Types ──────────────────────────────────────────────────────────────────
/** Where the lead came from — determines which Meta event we fire. */
type LeadSource = 'contact' | 'lead_magnet';

/** UTM block forwarded by the client. Mirrors lib/utm.ts → UtmParams. */
interface LeadUtm {
  source?:     string;
  medium?:     string;
  campaign?:   string;
  content?:    string;
  term?:       string;
  fbclid?:     string;
  gclid?:      string;
  capturedAt?: string;
}

interface LeadPayload {
  name:      string;
  phone:     string;
  email?:    string; // optional — only the lead_magnet form collects this today
  location?: string; // optional — future buyers may not have a property yet
  revenue?:  string;
  /** UUID generated by the client; shared with the browser Pixel for CAPI dedup. */
  eventId?:  string;
  /** Which funnel the lead came from. Defaults to "contact". */
  source?:   LeadSource;
  /** UTM/click-id attribution captured client-side from URL. */
  utm?:      LeadUtm;
  _hp?:      string; // honeypot — should always be empty
}

// ─── In-memory rate limiter ─────────────────────────────────────────────────
// Resets on cold start; sufficient for a server with persistent connections.
// For a stateless/serverless deployment use an external KV (e.g. Upstash Redis).
const rateLimitMap = new Map<string, { count: number; resetAt: number }>();
const RATE_LIMIT   = 3;                   // max submissions per window per IP
const RATE_WINDOW  = 60 * 60 * 1000;     // 1-hour rolling window

function isRateLimited(ip: string): boolean {
  const now   = Date.now();
  const entry = rateLimitMap.get(ip);

  if (!entry || now > entry.resetAt) {
    rateLimitMap.set(ip, { count: 1, resetAt: now + RATE_WINDOW });
    return false;
  }
  if (entry.count >= RATE_LIMIT) return true;
  entry.count++;
  return false;
}

// ─── Phone validation ───────────────────────────────────────────────────────
// Accepts: +351 followed by PT mobile/landline prefix + 8 digits, OR any
// international E.164 number (+[country][7-14 digits]).
function isValidPhone(phone: string): boolean {
  const cleaned = phone.replace(/[\s\-().]/g, '');
  // Portuguese mobile/landline: +351 9/2/3/6/7/8 + 8 digits (total 12 digits after +351)
  const ptPattern   = /^\+351[236789]\d{8}$/;
  // Generic international: + then 7–15 digits
  const intlPattern = /^\+[1-9]\d{6,14}$/;
  return ptPattern.test(cleaned) || intlPattern.test(cleaned);
}

// ─── HTML escape (for Telegram HTML mode + email body) ─────────────────────
function escHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

// ─── Telegram notification ──────────────────────────────────────────────────
async function sendTelegram(lead: LeadPayload): Promise<void> {
  const token  = process.env.TELEGRAM_BOT_TOKEN;
  const chatId = process.env.TELEGRAM_CHAT_ID;

  if (!token || !chatId) {
    console.warn('[LeadAPI] Telegram credentials missing — skipping Telegram notification');
    return;
  }

  // Optional UTM block — only emit if at least one field is present
  const utmLines = lead.utm ? formatUtmTextLines(lead.utm) : [];

  const lines = [
    `🚀 <b>New Lead for PortoPrime!</b>`,
    ``,
    `👤 <b>Name:</b> ${escHtml(lead.name)}`,
    `📞 <b>Phone:</b> ${escHtml(lead.phone)}`,
    lead.location ? `📍 <b>Location:</b> ${escHtml(lead.location)}` : null,
    lead.revenue  ? `💰 <b>Est. Revenue:</b> ${escHtml(lead.revenue)}/mo` : null,
    ...(utmLines.length > 0 ? ['', '🎯 <b>Source:</b>', ...utmLines] : []),
    ``,
    `🕐 <i>${new Date().toLocaleString('en-GB', { timeZone: 'Europe/Lisbon' })} (Lisbon)</i>`,
  ].filter(Boolean).join('\n');

  const res = await fetch(
    `https://api.telegram.org/bot${token}/sendMessage`,
    {
      method:  'POST',
      headers: { 'Content-Type': 'application/json' },
      body:    JSON.stringify({ chat_id: chatId, text: lines, parse_mode: 'HTML' }),
    },
  );

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Telegram API error ${res.status}: ${text}`);
  }
}

/** Formats UTM block as Telegram-safe lines. */
function formatUtmTextLines(utm: LeadUtm): string[] {
  const out: string[] = [];
  if (utm.source)   out.push(`  • source: ${escHtml(utm.source)}`);
  if (utm.medium)   out.push(`  • medium: ${escHtml(utm.medium)}`);
  if (utm.campaign) out.push(`  • campaign: ${escHtml(utm.campaign)}`);
  if (utm.content)  out.push(`  • content: ${escHtml(utm.content)}`);
  if (utm.term)     out.push(`  • term: ${escHtml(utm.term)}`);
  if (utm.fbclid)   out.push(`  • fbclid: ${escHtml(utm.fbclid)}`);
  if (utm.gclid)    out.push(`  • gclid: ${escHtml(utm.gclid)}`);
  return out;
}

// ─── Email notification (Resend) ────────────────────────────────────────────
// Uses RESEND_API_KEY (server-only env). Sends from notifications@portoprime.pt
// → LEAD_EMAIL_TO (default: alexxistu@gmail.com). DKIM/SPF for portoprime.pt
// must be configured in DNS (Vercel) — see CLAUDE.md → Resend Setup.
//
// Resend SDK is loaded lazily so the build doesn't fail when the package is
// not yet installed (e.g. during CI before `npm install` runs).
async function sendEmail(lead: LeadPayload): Promise<void> {
  const apiKey = process.env.RESEND_API_KEY;
  const from   = process.env.RESEND_FROM   || 'PortoPrime Leads <notifications@portoprime.pt>';
  const to     = process.env.LEAD_EMAIL_TO || 'alexxistu@gmail.com';

  if (!apiKey) {
    console.info('[LeadAPI] RESEND_API_KEY not set — skipping email notification');
    return;
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let Resend: any;
  try {
    // Lazy require so missing dependency doesn't crash the build.
    Resend = require('resend').Resend;
  } catch {
    console.warn('[LeadAPI] resend not installed — run: npm install resend');
    return;
  }

  const resend = new Resend(apiKey);
  const lisbonTime = new Date().toLocaleString('en-GB', { timeZone: 'Europe/Lisbon' });

  // Build optional UTM rows for the table
  const utmRows = lead.utm
    ? Object.entries({
        'utm_source':   lead.utm.source,
        'utm_medium':   lead.utm.medium,
        'utm_campaign': lead.utm.campaign,
        'utm_content':  lead.utm.content,
        'utm_term':     lead.utm.term,
        'fbclid':       lead.utm.fbclid,
        'gclid':        lead.utm.gclid,
      })
        .filter(([, v]) => v)
        .map(
          ([k, v], idx) => `
          <tr ${idx % 2 === 0 ? 'style="background:#fafafa;"' : ''}>
            <td style="padding:8px 8px;color:#888;font-family:monospace;font-size:12px;width:160px;">${k}</td>
            <td style="padding:8px 8px;color:#1B263B;font-family:monospace;font-size:12px;">${escHtml(String(v))}</td>
          </tr>`,
        )
        .join('')
    : '';

  const html = `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;background:#f4f4f4;padding:20px;border-radius:10px;">
      <!-- Header -->
      <div style="background:#1B263B;padding:28px 24px;border-radius:8px 8px 0 0;text-align:center;">
        <h1 style="color:#E0C397;margin:0;font-size:26px;letter-spacing:1px;">PortoPrime</h1>
        <p style="color:rgba(255,255,255,0.55);margin:6px 0 0;font-size:13px;">Lead Notification</p>
      </div>
      <!-- Body -->
      <div style="background:#ffffff;padding:28px 24px;border-radius:0 0 8px 8px;">
        <h2 style="color:#1B263B;font-size:20px;border-bottom:2px solid #E0C397;padding-bottom:10px;margin-top:0;">
          🚀 New Lead Received
        </h2>
        <table style="width:100%;border-collapse:collapse;font-size:14px;">
          <tr>
            <td style="padding:10px 0;color:#888;width:160px;vertical-align:top;">👤 Name</td>
            <td style="padding:10px 0;color:#1B263B;font-weight:bold;">${escHtml(lead.name)}</td>
          </tr>
          <tr style="background:#fafafa;">
            <td style="padding:10px 8px;color:#888;vertical-align:top;">📞 Phone</td>
            <td style="padding:10px 8px;color:#1B263B;font-weight:bold;">${escHtml(lead.phone)}</td>
          </tr>
          ${lead.email ? `
          <tr>
            <td style="padding:10px 0;color:#888;vertical-align:top;">✉️ Email</td>
            <td style="padding:10px 0;color:#1B263B;font-weight:bold;">${escHtml(lead.email)}</td>
          </tr>` : ''}
          ${lead.location ? `
          <tr style="background:#fafafa;">
            <td style="padding:10px 8px;color:#888;vertical-align:top;">📍 Location</td>
            <td style="padding:10px 8px;color:#1B263B;font-weight:bold;">${escHtml(lead.location)}</td>
          </tr>` : ''}
          ${lead.revenue ? `
          <tr>
            <td style="padding:10px 0;color:#888;vertical-align:top;">💰 Est. Revenue</td>
            <td style="padding:10px 0;font-weight:bold;font-size:18px;color:#C9A96E;">${escHtml(lead.revenue)}/mo</td>
          </tr>` : ''}
          <tr style="background:#fafafa;">
            <td style="padding:10px 8px;color:#888;vertical-align:top;">🔗 Source</td>
            <td style="padding:10px 8px;color:#1B263B;font-weight:bold;text-transform:uppercase;font-size:12px;letter-spacing:1px;">${escHtml(lead.source ?? 'contact')}</td>
          </tr>
        </table>

        ${utmRows ? `
        <!-- UTM attribution -->
        <h3 style="color:#1B263B;font-size:14px;margin:24px 0 10px;text-transform:uppercase;letter-spacing:1px;border-bottom:1px solid #eee;padding-bottom:6px;">
          🎯 Attribution
        </h3>
        <table style="width:100%;border-collapse:collapse;">
          ${utmRows}
        </table>` : ''}

        <!-- Timestamp -->
        <div style="margin-top:24px;padding:14px 16px;background:#f0f4f8;border-radius:6px;border-left:4px solid #E0C397;">
          <p style="margin:0;color:#666;font-size:12px;">Submitted: <strong>${lisbonTime}</strong> (Lisbon time)</p>
        </div>

        <!-- Action button -->
        <div style="margin-top:24px;text-align:center;">
          <a href="https://wa.me/351915481058"
             style="display:inline-block;background:#25D366;color:#ffffff;padding:13px 28px;
                    border-radius:8px;text-decoration:none;font-weight:bold;font-size:14px;">
            📱 WhatsApp this Lead
          </a>
        </div>
      </div>
      <!-- Footer -->
      <p style="text-align:center;color:#aaa;font-size:11px;margin-top:16px;">
        PortoPrime · Lisbon · Porto · Algarve · portoprime.pt
      </p>
    </div>
  `;

  // Plaintext fallback for Gmail Promotions filter heuristics + accessibility
  const text = [
    'New PortoPrime Lead',
    '',
    `Name:     ${lead.name}`,
    `Phone:    ${lead.phone}`,
    lead.email    ? `Email:    ${lead.email}`        : null,
    lead.location ? `Location: ${lead.location}`     : null,
    lead.revenue  ? `Revenue:  ${lead.revenue}/mo`   : null,
    `Source:   ${lead.source ?? 'contact'}`,
    ...(lead.utm ? ['', 'Attribution:'] : []),
    ...(lead.utm
      ? Object.entries(lead.utm)
          .filter(([, v]) => v)
          .map(([k, v]) => `  ${k}: ${v}`)
      : []),
    '',
    `Time: ${lisbonTime} (Lisbon)`,
  ]
    .filter(Boolean)
    .join('\n');

  const result = await resend.emails.send({
    from,
    to,
    subject: `🏠 New Lead: ${lead.name}${lead.location ? ` — ${lead.location}` : ''}`,
    html,
    text,
    // Help inbox providers thread admin notifications and not flag them as spam.
    headers: {
      'X-Entity-Ref-ID': lead.eventId ?? '',
    },
  });

  if (result?.error) {
    throw new Error(`Resend API error: ${result.error.message ?? JSON.stringify(result.error)}`);
  }
}

// ─── Meta CAPI helpers ──────────────────────────────────────────────────────
/**
 * Split a full-name string into first / last for hashing.
 * Best-effort only: takes the first token as firstName, the rest (if any) as lastName.
 * Meta allows either field to be absent.
 */
function splitName(full: string): { firstName?: string; lastName?: string } {
  const parts = full.trim().split(/\s+/);
  if (parts.length === 0) return {};
  if (parts.length === 1) return { firstName: parts[0] };
  return { firstName: parts[0], lastName: parts.slice(1).join(' ') };
}

/**
 * Build the CAPI user_data payload from the incoming request + parsed lead.
 * Extracts IP, User-Agent, and Facebook click/browser cookies (_fbc / _fbp).
 */
function buildUserDataFromRequest(
  req: NextRequest,
  lead: LeadPayload,
  fallbackIp: string,
): CapiUserData {
  const { firstName, lastName } = splitName(lead.name);

  // Facebook cookies set by the Pixel on the browser
  const fbc = req.cookies.get('_fbc')?.value;
  const fbp = req.cookies.get('_fbp')?.value;

  return {
    email:     lead.email,
    phone:     lead.phone && lead.phone !== '+000000000000' ? lead.phone : undefined,
    firstName,
    lastName,
    city:      lead.location,
    country:   'pt', // all traffic targets Portugal (Lisbon / Porto / Algarve)
    clientIp:  fallbackIp !== 'unknown' ? fallbackIp : undefined,
    userAgent: req.headers.get('user-agent') ?? undefined,
    fbc,
    fbp,
  };
}

/** Convert client UTM block to the CAPI custom_data shape. */
function toCapiUtm(utm?: LeadUtm): CapiUtmData | undefined {
  if (!utm) return undefined;
  const { capturedAt, ...rest } = utm;
  void capturedAt; // capturedAt is informational only; not forwarded to Meta
  return rest;
}

/**
 * Fire the appropriate Meta CAPI event for the given lead source.
 * Errors are thrown so the caller can log them; the lead itself never fails
 * because of a CAPI issue (caller wraps this in try/catch).
 */
async function fireCapiEvent(
  req: NextRequest,
  lead: LeadPayload,
  ip: string,
): Promise<{ ok: boolean; error?: string; skipped?: 'no_event_id' }> {
  if (!lead.eventId) {
    return { ok: false, skipped: 'no_event_id' };
  }

  const sourceUrl = req.headers.get('referer') ?? undefined;
  const userData  = buildUserDataFromRequest(req, lead, ip);
  const utm       = toCapiUtm(lead.utm);

  if (lead.source === 'lead_magnet') {
    return sendCompleteRegistrationEvent({
      eventId: lead.eventId,
      userData,
      sourceUrl,
      utm,
    });
  }
  return sendContactEvent({
    eventId:  lead.eventId,
    userData,
    sourceUrl,
    revenue:  lead.revenue,
    utm,
  });
}

// ─── POST /api/lead ─────────────────────────────────────────────────────────
export async function POST(req: NextRequest) {
  try {
    // ── Rate limit by IP ──────────────────────────────────────────────────
    const ip = (
      req.headers.get('x-forwarded-for')?.split(',')[0].trim() ??
      req.headers.get('x-real-ip') ??
      'unknown'
    );
    if (isRateLimited(ip)) {
      return NextResponse.json({ error: 'rate_limit' }, { status: 429 });
    }

    // ── Parse body ────────────────────────────────────────────────────────
    let body: LeadPayload;
    try {
      body = await req.json();
    } catch {
      return NextResponse.json({ error: 'invalid_body' }, { status: 400 });
    }

    const { name, phone, email, location, revenue, eventId, source, utm, _hp } = body;

    // ── Honeypot check — real users never touch this hidden field ─────────
    if (_hp) {
      // Return 200 so bots don't know they were caught
      return NextResponse.json({ ok: true });
    }

    // ── Source-aware validation ───────────────────────────────────────────
    // Contact form  → name + phone required (phone validated)
    // Lead magnet   → email required, name/phone not collected
    const normalizedSource: 'contact' | 'lead_magnet' =
      source === 'lead_magnet' ? 'lead_magnet' : 'contact';

    if (normalizedSource === 'lead_magnet') {
      if (!email?.trim()) {
        return NextResponse.json({ error: 'missing_email' }, { status: 400 });
      }
    } else {
      if (!name?.trim() || !phone?.trim()) {
        return NextResponse.json({ error: 'missing_fields' }, { status: 400 });
      }
      if (!isValidPhone(phone)) {
        return NextResponse.json({ error: 'invalid_phone' }, { status: 422 });
      }
    }

    // For lead_magnet, name/phone may be absent — we substitute placeholders so
    // the existing Telegram/email senders don't choke. CAPI uses only email.
    const lead: LeadPayload = {
      name:     name?.trim()    || (normalizedSource === 'lead_magnet' ? 'Lead Magnet Subscriber' : ''),
      phone:    phone?.trim()   || '+000000000000',
      email:    email?.trim()   || undefined,
      location: location?.trim() || undefined,
      revenue:  revenue?.trim()  || undefined,
      eventId:  eventId?.trim() || undefined,
      source:   normalizedSource,
      utm:      utm && typeof utm === 'object' ? utm : undefined,
    };

    // ── Send Telegram (primary — must succeed) ───────────────────────────
    await sendTelegram(lead);

    // ── Send email (secondary — non-fatal) ───────────────────────────────
    sendEmail(lead).catch((err) =>
      console.error('[LeadAPI] Email send failed:', err),
    );

    // ── Send Meta CAPI event (non-fatal — server-side dedup counterpart) ─
    // Awaited so we can log the result synchronously and guarantee the
    // request lands before the process moves on. CAPI errors never fail
    // the lead itself — Telegram already succeeded above.
    try {
      const capiResult = await fireCapiEvent(req, lead, ip);
      if (capiResult.ok) {
        // Success log only in dev/preview — production stays clean.
        if (process.env.NODE_ENV !== 'production') {
          console.info('[LeadAPI] Meta CAPI event sent', {
            source:  lead.source,
            eventId: lead.eventId ?? 'none',
          });
        }
      } else if (capiResult.skipped) {
        console.warn(`[LeadAPI] Meta CAPI skipped — reason: ${capiResult.skipped}`);
      } else {
        console.error(`[LeadAPI] Meta CAPI failed — reason: ${capiResult.error ?? 'unknown'}`);
      }
    } catch (err) {
      console.error('[LeadAPI] Meta CAPI send failed:', err);
    }

    return NextResponse.json({ ok: true });

  } catch (err) {
    console.error('[LeadAPI] Unhandled error:', err);
    return NextResponse.json({ error: 'server_error' }, { status: 500 });
  }
}
